// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: cryptowatch

#include "../ui.h"

void ui_currtime_screen_init(void)
{
    ui_currtime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_currtime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_currtime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_currtime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day2 = lv_label_create(ui_currtime);
    lv_obj_set_width(ui_day2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day2, 0);
    lv_obj_set_y(ui_day2, 60);
    lv_obj_set_align(ui_day2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day2, "12/22");
    lv_obj_set_style_text_font(ui_day2, &ui_font_NerdFont18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time2 = lv_label_create(ui_currtime);
    lv_obj_set_width(ui_time2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time2, 0);
    lv_obj_set_y(ui_time2, -20);
    lv_obj_set_align(ui_time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time2, "00:00");
    lv_obj_set_style_text_color(ui_time2, lv_color_hex(0x7EF70C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time2, &ui_font_NerdFont50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_flag(ui_currtime, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_opa(ui_currtime, LV_OPA_TRANSP, 0);
    lv_obj_add_event_cb(ui_currtime, ui_event_to_graph, LV_EVENT_ALL, NULL);

}
