// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: cryptowatch

#include "../ui.h"

void ui_graph_screen_init(void)
{
    ui_graph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Make the entire screen clickable
    lv_obj_add_flag(ui_graph, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(ui_graph, ui_event_to_status, LV_EVENT_CLICKED, NULL);  // New general screen callback

    LV_IMAGE_DECLARE(bg_candle);
    lv_obj_t * img1 = lv_image_create(ui_graph);
    lv_image_set_src(img1, &bg_candle);
    lv_obj_align(img1, LV_ALIGN_CENTER, 0, 0);

    ui_day = lv_label_create(ui_graph);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, 9);
    lv_obj_set_y(ui_day, 6);
    lv_label_set_text(ui_day, "12/22");
    lv_obj_set_style_text_color(ui_day, lv_color_hex(0xD1C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day, &ui_font_NerdFont18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_graph);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 79);
    lv_obj_set_y(ui_time, 4);
    lv_label_set_text(ui_time, "00:00");
    lv_obj_set_style_text_font(ui_time, &ui_font_NerdFont22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_crypto = lv_label_create(ui_graph);
    lv_obj_set_width(ui_crypto, 50);   /// 1
    lv_obj_set_height(ui_crypto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_style_text_align(ui_crypto , LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_x(ui_crypto, -5);
    lv_obj_set_y(ui_crypto, 12);
    lv_obj_set_align(ui_crypto, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_crypto, crypto);
    lv_obj_set_style_text_color(ui_crypto, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_crypto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_crypto, &ui_font_NerdFont18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cog = lv_label_create(ui_graph);
    lv_obj_set_width(ui_cog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cog, 203);
    lv_obj_set_y(ui_cog, 5);
    lv_label_set_text(ui_cog, "x");
    lv_obj_set_style_text_color(ui_cog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cog, &ui_font_FA38, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Keep the cog clickable with its own callback
    lv_obj_add_flag(ui_cog, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_opa(ui_cog, LV_OPA_TRANSP, 0);
    lv_obj_add_event_cb(ui_cog, ui_event_to_settings, LV_EVENT_CLICKED, NULL);
}
