// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: cryptowatch

#include "../ui.h"

void ui_weather_screen_init(void)
{
    ui_weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_weather, LV_OBJ_FLAG_CLICKABLE);

    LV_IMAGE_DECLARE(bg_candle);
    lv_obj_t * img1 = lv_image_create(ui_weather);
    lv_image_set_src(img1, &bg_candle);
    lv_obj_align(img1, LV_ALIGN_CENTER, 0, 0);

    ui_day3 = lv_label_create(ui_weather);
    lv_obj_set_width(ui_day3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day3, 9);
    lv_obj_set_y(ui_day3, 6);
    lv_label_set_text(ui_day3, "12/22");
    lv_obj_set_style_text_color(ui_day3, lv_color_hex(0xD1C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day3, &ui_font_NerdFont18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time3 = lv_label_create(ui_weather);
    lv_obj_set_width(ui_time3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time3, 79);
    lv_obj_set_y(ui_time3, 4);
    lv_label_set_text(ui_time3, "00:00");
    lv_obj_set_style_text_font(ui_time3, &ui_font_NerdFont22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather_icon = lv_label_create(ui_weather);
    lv_obj_set_width(ui_weather_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather_icon, -12);
    lv_obj_set_y(ui_weather_icon, 8);
    lv_obj_set_align(ui_weather_icon, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_weather_icon, "s");
    lv_obj_set_style_text_color(ui_weather_icon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_icon, &ui_font_FA38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature = lv_label_create(ui_weather);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, 35);
    lv_obj_set_y(ui_temperature, 93);
    lv_label_set_text(ui_temperature, "25C");
    lv_obj_set_style_text_color(ui_temperature, lv_color_hex(0x7EF70C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature, &ui_font_NerdFont50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherindicator = lv_label_create(ui_weather);
    lv_obj_set_width(ui_weatherindicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherindicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherindicator, 182);
    lv_obj_set_y(ui_weatherindicator, 86);
    lv_label_set_text(ui_weatherindicator, "n");
    lv_obj_set_style_text_color(ui_weatherindicator, lv_color_hex(0x7EF70C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherindicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherindicator, &ui_font_Weather150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_location = lv_label_create(ui_weather);
    lv_obj_set_width(ui_location, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_location, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_location, 40);
    lv_obj_set_y(ui_location, 170);
    lv_label_set_text(ui_location, location);
    lv_obj_set_style_text_color(ui_location, lv_color_hex(0x7EF70C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_location, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_location, &ui_font_NerdFont22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cog1 = lv_label_create(ui_weather);
    lv_obj_set_width(ui_cog1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cog1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cog1, 203);
    lv_obj_set_y(ui_cog1, 5);
    lv_label_set_text(ui_cog1, "x");
    lv_obj_set_style_text_color(ui_cog1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cog1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cog1, &ui_font_FA38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_flag(ui_cog1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_opa(ui_cog1, LV_OPA_TRANSP, 0);
    lv_obj_add_event_cb(ui_weather, ui_event_to_currtime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cog1, ui_event_to_status, LV_EVENT_ALL, NULL);

}
