// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: cryptowatch

#ifndef _CRYPTOWATCH_UI_H
#define _CRYPTOWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_graph
void ui_graph_screen_init(void);
extern lv_obj_t * ui_graph;
extern lv_obj_t * ui_background;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_crypto;
extern lv_obj_t * ui_Chart1;
void ui_event_to_settings(lv_event_t * e);
void ui_event_to_status(lv_event_t * e);
extern lv_obj_t * ui_cog;

// CUSTOM VARIABLES

// SCREEN: ui_currtime
void ui_currtime_screen_init(void);
void ui_event_to_graph(lv_event_t * e);
extern lv_obj_t * ui_currtime;
extern lv_obj_t * ui_day2;
extern lv_obj_t * ui_time2;
// CUSTOM VARIABLES

// SCREEN: ui_weather
void ui_weather_screen_init(void);
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_background2;
extern lv_obj_t * ui_day3;
extern lv_obj_t * ui_time3;
extern lv_obj_t * ui_weather_icon;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_weatherindicator;
extern lv_obj_t * ui_location;
void ui_event_to_currtime(lv_event_t * e);
extern lv_obj_t * ui_cog1;
// CUSTOM VARIABLES

// SCREEN: ui_status
void ui_status_screen_init(void);
extern lv_obj_t * ui_status;
extern lv_obj_t * ui_background1;
extern lv_obj_t * ui_day1;
extern lv_obj_t * ui_time1;
extern lv_obj_t * ui_crypto1;
extern lv_obj_t * ui_cryptovalue;
extern lv_obj_t * ui_cryptohigh;
extern lv_obj_t * ui_cryptolow;
void ui_event_to_weather(lv_event_t * e);
extern lv_obj_t * ui_cog3;


// SCREEN: ui_settings
void ui_settings_screen_init(void);
extern lv_obj_t * ui_settings;
extern lv_obj_t * kb;
extern lv_obj_t * kb_cont;
extern lv_obj_t * ssid_ta;
extern lv_obj_t * password_ta;
extern lv_obj_t * lat_ta;
extern lv_obj_t * long_ta;
extern lv_obj_t * crypto_ta;
extern lv_obj_t * timespan_ta;
extern lv_obj_t * loc_ta;


extern char* ssid;
extern char* password;
extern char* latitude;
extern char* longitude;
extern char* crypto;
extern char* timespan;
extern char* location;

void load_preferences();
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg_candle_png);    // assets/bg_candle.png

// FONTS
LV_FONT_DECLARE(ui_font_NerdFont18);
LV_FONT_DECLARE(ui_font_NerdFont50);
LV_FONT_DECLARE(ui_font_FA38);
LV_FONT_DECLARE(ui_font_NerdFont22);
LV_FONT_DECLARE(ui_font_Weather150);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
